package chp5_Exceptions.creatingexceptions;

public class Exercise2BreakingTheLaw {

    /*
    In this exercise, we are going to create our own checked exception class.
    We will define a class and then experiment by provoking that exception,
    logging its results, and then analyzing them:
     */

    public static void main(String[] args) throws MyException {
        //we have to generate a code that will provoke an exception,
        //such as NullPointerException, when trying to get the length of a String
        //initialized to null, catch it, then throw it away using our newly created class:

        String s = null;

        try {
            System.out.println(s.length());
        } catch (NullPointerException ne) {
            throw new MyException("Exception: my exception happened");
        }

        /*
        What will make the output slightly more informative
        is that it will now include information about the exception
        that generated our own NullPointerException:/
         */

        /*
        /Using to throw to wrap an exception into your own exception class,
        can be very handy when dealing with a large codebase and having to look
        for the exceptions generated by your code in a long log file,
        or similar
         */





    }



}



